name: Django-app workflow

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install dependencies
      run: | 
        python -m pip install --upgrade pip 
        pip install flake8 pep8-naming flake8-broken-line flake8-return flake8-isort
        pip install -r requirements.txt 

    - name: Test with flake8 and django tests
      run: |
        python -m flake8
        cd infra_project/
        python manage.py test

  build_and_push_to_docker_hub:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Check out the repo
        # Проверка доступности репозитория Docker Hub для workflow
        uses: actions/checkout@v2 
      - name: Set up Docker Buildx
        # Вызов сборщика контейнеров docker
        uses: docker/setup-buildx-action@v1 
      - name: Login to Docker 
        # Запуск скрипта авторизации на Docker Hub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }} 
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to Docker Hub
        # Пуш образа в Docker Hub 
        uses: docker/build-push-action@v2 
        with:
          push: true
          tags: cocosi383/infra_actions

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push_to_docker_hub
    steps:
    - name: executing remote ssh commands to deploy
      uses: appleboy/ssh-action@master
      with:
        host: 51.250.100.101
        username: cocosi
        key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDXq579cd6mCULlsFSpL+3NNfJhAmglb1oHVbOZAaxGvRS+W0ySEDdecg7Cw8gcoCpwUEPdalJ/eQbHtca6ArIs2vsShjgfbLEWMUTrXOJgB/FIFBrH+xOshfMaJJpPy4Gwmu4/hV81QoYUdxeDpjAwOGO4MhSU6n+hLiwAyP3X5z24NC8zU4WVbfSXhX2U3FZJ7X8A6oec1xa8jqJJjcHA/JEbKkXIM4XSkynzuIEMEwP+8ap0UyS/GAl3/UQ+lX/X5O2WnQlLUUe9p4TsyPJiX9zQB3NUdIm038TXC6pojoj3NltsEwaXYr3Da6uYvOpxlwA4cfUB2cbYh+Kc6nrjXxqm93+nk07kCDB4g05XLoJRAlbMSzflGSsLiiU9tw+eLzESr0qpxup6gfulqos85TeT8uIs/fBPnfHA4c+nZAqB5x11MjjpdMriR/OAOaR1L43DZ5zmediAR7865wJmGOZr3FP7rQxwExBMuVfB07ZOFPRU6RSC9s+rFMfKOJc= Сергей@Gray
        script: |
          # Выполняет pull образа с DockerHub
          sudo docker pull cocosi383/infra_actions
          #остановка всех контейнеров
          sudo docker stop ps -a -q | xargs sudo docker stop
          sudo docker run --rm -d -p 5000:5000 cocosi383/infra_actions